import axios from "axios";

export const generateQuiz = async (topic) => {
  try {
    const apiKey = import.meta.env.VITE_OPENROUTER_API_KEY;

    if (!apiKey) {
      console.error(" OpenRouter API key missing.");
      return "API key not found.";
    }

    const response = await axios.post(
      "https://openrouter.ai/api/v1/chat/completions",
      {
        model: "mistralai/mistral-7b-instruct",
        messages: [
          {
            role: "user",
            content: `Generate 10 multiple-choice quiz questions on the topic "${topic}".
Each question should follow this format **exactly**:

1. Question text?
A) Option A
B) Option B
C) Option C
D) Option D
Correct Answer: <Only one of A/B/C/D>

Only return the quiz in this format. No explanations, titles, or notes.`,
          },
        ],
        temperature: 0.7,
      },
      {
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
        },
      }
    );

    const output = response.data?.choices?.[0]?.message?.content;

    if (!output || output.trim() === "") {
      console.error(" No quiz generated by AI.");
      return "Failed to generate quiz. Try again.";
    }

    console.log(" Raw AI Quiz Output:\n", output); 
    return output.trim();
  } catch (error) {
    if (error.response) {
      console.error(" OpenRouter API Error:", error.response.data);
    } else {
      console.error(" Unknown Error:", error.message);
    }

    return "Failed to generate quiz. Try again.";
  }
};
